### ISSUE TITLE
API v3

### ISSUE THREAD

**Issue by morphinapg** [HristoKolev/TvDbSharper#14] opened 2019-11-15 04:25 UTC
TVDB just pushed out v3 of their api and a lot of people are having issues with it. I don't know whether TVDBsharper actually needs to change anything in order to continue functionality, but I currently can't log in with my API key. It's possible this may be a glitch on TVDB's side, but it would probably be best to make sure TVDBSharper was fully compatible with v3 anyway.

**Comment by morphinapg** [comment] 2019-11-15 09:01
I figured out a solution to the authentication issue. I needed to use 

AuthenticateAsync(string apiKey);

instead of 

AuthenticateAsync(string apiKey, string username, string userKey);

but it's still probably a good idea to verify all functionality still works with v3.

**Comment by ZuiMelanieForno** [comment] 2019-11-15 20:28
Hi.

I can confirm the Token is returned with the "simple" API-Key parameter.

But all Images needed to be (re)downloaded, by my Caching-System.

I am not shure if the Cache was wiped, because of the Fails logins.

What is not working atm are the Season Images. I will try it out and if I find the time I will report.

c.u. Zui

**Comment by morphinapg** [comment] 2019-11-16 02:24
I know SeriesSearchResult.Banner now results in a Poster image, instead of Banner. This was also confirmed on the swagger page. I had to do

`var imgs = await client.Series.GetImagesAsync(ID, new TvDbSharper.Dto.ImagesQuery() { KeyType = TvDbSharper.Dto.KeyType.Series });
`
and then use

`imgs.Data.First().FileName;
`
for the Banner image. I don't use Season images so I don't know about those, but there definitely seem to be some things that are different now.

**Comment by ZuiMelanieForno** [comment] 2019-11-21 17:19
Hi.

I got the Images back again, by changing the Base URL to:
https://artworks.thetvdb.com/banners/
then I just concatinate the resulting Imagepath.

I stopped to use the "derefferer" in the URL´s if I wanted to go a certain link like Season by number or the Series URL.

Also to note, sometimes the "Slug"-Value is not a String it is just the TVDBID, so please do a check beforehand.

But the TvDbSharper seems to work still correct against the API.

c.u. Zui

**Comment by HristoKolev** [comment] 2019-12-23 21:44
For some reason I did not receive notifications for issues on this repo. I will take a look as soon as possible.

**Comment by ZuiMelanieForno** [comment] 2019-12-23 22:15
Hi.
Nice to hear from You.
As I can see the API v3 changes are not big, only the "API Key Credentials" has changed.

Sidenote:
Info for all who have used the API Keys should check the new API requirements on "TheTvDb.com".

So your TvDbSharper is working fine.
It was more of a hickup on the API-Side.
The Image Paths are a little bit different now.

I would suggest to change the Nuget-Package that it also supports "v3".

 Can I use this oportunity to request a Image-Collection-Feature?

I would like to use a Service-Layer to get all Images in a Data-Structure, to get all Images returned, in a convenient Async-Function.

Please. With alcoholfree-Eggnog and Sugarcoat ontop... :)
  
 c.u. and happy Holidays and a successful new Year.

**Comment by HristoKolev** [comment] 2020-01-05 16:27
I have started work on the next version.

The current plan is: 
* Verify that the each API-calling method returns without error.
* Add any missing fields to the Dto classes, and remove any that are not used anymore.
* Add new endpoints where it's needed.
* Replace the old http API with the new one.

Any other suggestions and/or requests?

**Comment by HristoKolev** [comment] 2020-01-09 18:46
Ok. v3 is released. Changes can be found in CHANGELOG.md.  I'm closing this issue. If there are any problems, please open a new one.

**Closed by HristoKolev** 2020-01-09 18:46 UTC
